DjangoWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('console.urls')),
]

console/urls.py
from django.conf.urls import include, url
from console.toolset.vhost import update_db_init
from django.contrib.auth import views as auth_views
from . import views
from . import ajax

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'console/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', views.dash_vm),
    url(r'^vmachine/$', views.dash_vm),
    url(r'vhost/$', views.dash_vhost),
    url(r'^vmachine/new/$',views.form_vm),
    url(r'^vhost/new/$', views.form_vhost),
    url(r'^vhost/datastore/$', views.dash_datastore),
    url(r'^vhost/datastore/new/$', views.form_datastore),
    url(r'^vhost/network/$', views.dash_network),
    url(r'^vhost/network/new/$', views.form_network),
    url(r'^ajax/startvm/$', ajax.start_vm),
    url(r'^ajax/stopvm/$', ajax.stop_vm),
    url(r'^ajax/pausevm/$', ajax.pause_vm),
    url(r'^ajax/mngsnap/$', ajax.mng_snap),
    url(r'^ajax/mksnap/$', ajax.mk_snap),
    url(r'^ajax/delsnap/?$', ajax.del_snap),
    url(r'^ajax/rstsnap/$', ajax.rst_snap),
    url(r'^ajax/modifyvm/$', ajax.modify_vm),
    url(r'^ajax/clonevm/$', ajax.clone_vm),
    url(r'^ajax/deletevm/$', ajax.delete_vm),
    url(r'^ajax/deletevh/$', ajax.delete_vhost),
    url(r'^ajax/delnet/?$', ajax.del_net),
    url(r'^ajax/deldstore/?$', ajax.del_dstore),
    url(r'^ajax/vm_update_query/$', ajax.vm_update_query),
    url(r'^ajax/vhost_update_query/$', ajax.vhost_update_query),
    url(r'^ajax/net_update_query/$', ajax.net_update_query),
    url(r'^ajax/dstore_update_query/$', ajax.dstore_update_query),
    url(r'^ajax/updatedb/$', ajax.updatedb),
    url(r'^ajax/form_vm/$', ajax.form_vm),
    url(r'^ajax/control_vm/$', ajax.control_vh),
    url(r'^ajax/remote/$', ajax.remote),
]


update_db_init()

console/models.py
import uuid
from django.db import models
from django.utils import timezone

# Models Vendor

class VType(models.Model):

    VBOX = 'VB'
    ZONES = 'ZN'
    ESX = 'VW'

    VENDOR_CHOICES = (
        (VBOX, 'Oracle Virtualbox'),
        (ZONES, 'Oracle Solaris'),
        (ESX, 'Vmware ESXi'),
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    version = models.CharField(max_length=50)
    vendor = models.CharField(max_length=2, choices=VENDOR_CHOICES,default=VBOX)

    def __str__(self):
        return self.name

# Models Virtual Hosts

class VHost(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    ipaddr = models.GenericIPAddressField (protocol='ipv4')
    VType = models.ForeignKey(VType)  # Lista de Vbox,ESXi, Zones
    user = models.CharField(max_length=10)
    sshkey = models.CharField(max_length=255)   # Mirar si existe un modelo especifco
    sshport = models.PositiveIntegerField(blank=True)
    isopath = models.CharField(max_length=100)



    def __str__(self):
        return self.name

class OsType(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=255)
    VType = models.ForeignKey(VType)

    def __str__(self):
        return self.name

class Datastore(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, null=False)
    dpath = models.CharField(max_length=100, null=False)
    VHost = models.ForeignKey(VHost)

    def __str__(self):
        return self.name

class VSwitch(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    VHost = models.ForeignKey(VHost)
    type = models.CharField(max_length=30, blank=True, null=True)
    phy_iface = models.CharField(max_length=7, blank=True, null=True)

class Medium(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    dpath = models.CharField(max_length=100)
    VHost = models.ForeignKey(VHost)

    def __str__(self):
        return self.name

'''
class Mediums(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
'''

# Models Virtual Machines

class VMachine(models.Model):



    RUNNING = 'RN'
    POWEROFF = 'PW'
    PAUSE = 'PA'

    STATE_CHOICES = (
        (RUNNING, 'running'),
        (POWEROFF, 'poweroff'),
        (PAUSE, 'paused'),
    )


    INSTALLED_CHOICES = (
        ('OK', 'OK'),
        ('KO', 'KO'),
    )

    id = models.AutoField(primary_key=True)
    vuuid = models.CharField(max_length=36) #change name to UUID
    name = models.CharField(max_length=30)
    cpu = models.PositiveIntegerField()
    mem = models.PositiveIntegerField() # EN MB
    VHost = models.ForeignKey(VHost)
    uptime = models.CharField(max_length=50,blank=True,null=True)
    state = models.CharField(max_length=2, choices=STATE_CHOICES,default='PW')
    OsType = models.ForeignKey(OsType,models.SET_NULL,blank=True,null=True)
    Datastore = models.ForeignKey(Datastore, models.SET_NULL, blank=True, null=True)
    rdport = models.PositiveIntegerField(blank=True, null=True)
    rdpuser = models.CharField(max_length=15,blank=True, null=True)
    rdppass = models.CharField(max_length=50,blank=True, null=True)
    installed = models.CharField(max_length=2, choices=INSTALLED_CHOICES,default='KO')
    VSwitch = models.ForeignKey(VSwitch, models.SET_NULL, blank=True, null=True,)


    #Remote_Admin = models.ForeignKey(Remote_Admin)  #TODO


    def __str__(self):
        return self.name

class VDisk(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    VMachine = models.ForeignKey(VMachine)
    size = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Snapshot(models.Model):

    id = models.AutoField(primary_key=True)
    suuid = models.CharField(max_length=36)
    name = models.CharField(max_length=30)
    VMachine = models.ForeignKey(VMachine)
    current = models.BooleanField(default=False)


class Remote_Admin(models.Model):

    id = models.AutoField(primary_key=True)
    VHost = models.ForeignKey(VHost)
    rdport = models.PositiveIntegerField(null=True)
    used = models.BooleanField(default=False)

# Model Logs

class Log(models.Model):

    id = models.AutoField(primary_key=True)
    message = models.CharField(max_length=255, blank=True, null=True)


'''
Borrar si no se usa

class VBOX_IFACE(models.Model): #TEST

    NAT = 'NT'
    INTNET = 'IT'
    BRIGED = 'BR'

    TYPE_CHOICES = (
        (NAT, 'Nat Network'),
        (INTNET, 'Internal Network'),
        (BRIGED, 'Bridged Network'),
    )


    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES,default=NAT)
    VMachine = models.ForeignKey(VMachine)
    driver = models.CharField(max_length=30)
    int_net = models.CharField(max_length=30, blank=True, null=True)
    phy_iface = models.CharField(max_length=7, blank=True, null=True)


class Ifaces(models.Model):  #Borrar si no usasda

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    VHost = models.ForeignKey(VHost)







'''

console/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.html import escape
from django.http import Http404, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import VMachine, VHost, VType, Datastore, OsType, VSwitch, Medium # Borrar si no se usa Ifaces, VBOX_IFACE, VDisk
from .forms import VHForm, DSForm
from .toolset.vbox import vbox_info, vbox_create, vbox_modify, vbox_create_dstore, vbox_delete_vm
from .toolset.esx import esx_info, esx_create_vm, esx_create_net, esx_modify
from .toolset.zones import zone_info, zone_create_vm, zone_create_net, zone_create_dstore
from .toolset.vhost import vhost_info, update_model


# Create your views here.
@login_required()
def dash_vm(request):

    update_model(option="update_state")
    update_model(option="snap_shot")
    dbmachines = VMachine.objects.all()
    VV = VType.objects.order_by('name')

    return render(request, 'console/dash-vm.html', {'vm':dbmachines,'vv': VV})

@login_required(login_url='/login/')
def form_vm(request):

    if request.is_ajax() and request.POST:

        dstore = Datastore.objects.get(id=int(request.POST.get('datastore')))
        os = OsType.objects.get(id=int(escape(request.POST.get('ostype'))))
        vsw = VSwitch.objects.get(id=int(escape(request.POST.get('vswitch'))))

        vmdata = {
            'name': escape(request.POST.get('name')),
            'vhost': int(escape(request.POST.get('vhost'))),
            'datastore' : dstore.dpath,
            'cpu' : escape(request.POST.get('cpu')),
            'mem' : escape(request.POST.get('mem')),
            'ostype' : os.name,
            'rdpport' : escape(request.POST.get('rdpport')),
            'dsize': escape(request.POST.get('dsize')),
            'driver': escape(request.POST.get('driver')),
            'net' : vsw.name,
        }

        vhost_id = vmdata['vhost']
        vmname = vmdata['name']


        if not VMachine.objects.filter(VHost_id=vhost_id,name=vmname).exists():

            VH = VHost.objects.get(id=vhost_id)

            if VH.VType.vendor == "VB":

                dvd = Medium.objects.get(id=escape(request.POST.get('image')))

                vmdata['type']=vsw.type
                vmdata['iface']=vsw.phy_iface
                vmdata['net']=vsw.name
                vmdata['image'] = dvd.dpath + "/" + dvd.name




                if vbox_create(vhost=VH,vm=vmdata):
                    data = {
                        'msg': 'The Virtual Machine has been created. Please click close to continue',
                    }
                    return JsonResponse(data)
                else:
                    data = {
                        'msg': 'Error: The Virtual Machine has not been created. Please contact with the administrator',
                    }
                    return JsonResponse(data)



            elif VH.VType.vendor == "VW":

                vmdata['vsw_id']=vsw.id
                msg = esx_create_vm(vhost=VH,vm=vmdata)

                if msg == "OK":
                    data = {
                    'msg': 'The Virtual Machine has been created. Please click close to continue',
                    }
                    return JsonResponse(data)
                else:

                    data = {
                    'msg': 'Error: The Virtual Machine has not been created. Please contact with the administrator',
                    }
                    return JsonResponse(data)


            elif VH.VType.vendor == "ZN":

                if zone_create_vm(vhost=VH,vm=vmdata):

                    data = {
                        'msg': 'The Virtual Machine has been created. Please click close to continue',
                    }
                    return JsonResponse(data)
                else:
                    data = {
                        'msg': 'Error: The Virtual Machine has not been created. Please contact with the administrator',
                    }
                    return JsonResponse(data)
    else:

        VH = VHost.objects.all()

        return render(request, 'console/form_vmachine.html', {'VH': VH})

@login_required(login_url='/login/')
def dash_vhost(request):

    vhosts = VHost.objects.order_by('VType')
    VV = VType.objects.order_by('name')

    virtualhost=[]
    for item in vhosts:

        data={
            'id' : item.id,
            'name' : item.name,
            'VType': item.VType,
            'ipaddr': item.ipaddr,
            'cpu': vhost_info(option="cpu",vhost=item),
            'mem': vhost_info(option="mem",vhost=item),
            'uptime': vhost_info(option="uptime",vhost=item)
        }
        virtualhost.append(data)

    return render(request, 'console/dash-vh.html', {'vh': virtualhost, 'vv': VV})

@login_required(login_url='/login/')
def form_vhost (request):

    if request.is_ajax() and request.method == "POST":



        ajax_id = int(escape(request.POST.get('vhostid')))
        VH = VHost.objects.get(id=ajax_id)
        VH.name = escape(request.POST.get('name'))
        VH.ipaddr = escape(request.POST.get('ipaddr'))
        VH.isopath = escape(request.POST.get('isopath'))
        VH.sshkey = escape(request.POST.get('sshkey'))
        VH.sshport = int(escape(request.POST.get('sshport')))
        VH.save()

        data = {
            'msg': 'The Virtual Host' + VH.name + ' has been modified',
            'URI': '/vhost/',
        }
        return JsonResponse(data)

    elif not request.is_ajax() and request.method == "POST":
        form = VHForm(request.POST)
        if form.is_valid():
            vh = form.save(commit=False)
            vh.save()
            return redirect('/vhost')

    else:
        form = VHForm()

    return render(request, 'console/form_vhost.html', {'form': form})

@login_required(login_url='/login/')
def dash_datastore(request):


    ds = Datastore.objects.all()
    dstore = []

    for item in ds:




        VH = VHost.objects.get(id=item.VHost.id)

        dsize = vhost_info(option='dstore_info',vhost=VH,dpath=item.dpath)


        data = {
            'id' : item.id,
            'vhost': item.VHost.name,
            'vendor': item.VHost.VType.name,
            'name': item.name,
            'dpath': item.dpath,
            'dsize_total': int(int(dsize['size'])/1024),
            'dsize_free': int(int(dsize['free'])/1024),
            'dsize_use': dsize['use'],
        }
        dstore.append(data)

    # Parameter to be used in the web template
    VH = VHost.objects.order_by('name')


    return render(request, 'console/dash-dstore.html', {'dstore': dstore, 'vhosts': VH})

@login_required(login_url='/login/')
def form_datastore(request):

    if request.is_ajax() and request.POST:
        vhost_id = int(escape(request.POST.get('vhost')))
        ds_name = escape(request.POST.get('name'))
        VH = VHost.objects.get(id=vhost_id)

        if VH.VType.vendor == "VB":
            dpath = escape(request.POST.get('dpath'))
        elif VH.VType.vendor == "ZN":
            zpool = escape(request.POST.get('dpath'))
            dpath = "/" + zpool + "/" + ds_name

        else:
            return Http404

        if not Datastore.objects.filter(VHost__id=vhost_id,name=ds_name,dpath=dpath).exists():

            if VH.VType.vendor == "VB":
                if vbox_create_dstore(vhost=VH,dname=ds_name,dpath=dpath):

                    new_ds = Datastore(
                        name = ds_name,
                        VHost = VH,
                        dpath = dpath,
                    )
                    new_ds.save()
                    data = {
                        'msg': "The new Datastore has been created in the DB",
                        'URI': "/vhost/datastore",
                    }
                else:
                    data = {
                        'msg': "There is been an error creating the Datastore. Please contact de Administrator",
                        'URI': "/vhost/datastore",
                    }
            elif VH.VType.vendor == "ZN":
                if zone_create_dstore(vhost=VH, dname=ds_name, zpool=zpool):

                    new_ds = Datastore(
                        name=ds_name,
                        VHost=VH,
                        dpath=dpath,
                    )
                    new_ds.save()
                    data = {
                        'msg': "The new Datastore has been created in the DB",
                        'URI': "/vhost/datastore",
                    }
                else:
                    data = {
                        'msg': "There is been an error creating the Datastore. Please contact de Administrator",
                        'URI': "/vhost/datastore",
                    }
            else:
                return Http404

        else:
            data = {
                'msg': "The Datastore already exists",
                'URI': "/vhost/datastore",
            }
        return JsonResponse(data)

    else:
        return Http404

@login_required(login_url='/login/')
def dash_network(request):

    vsw = VSwitch.objects.all()
    VH = VHost.objects.order_by('name')

    return render(request, 'console/dash-network.html', {'vswitch': vsw, 'vhosts': VH})

@login_required(login_url='/login/')
def form_network(request):

    if request.is_ajax() and request.POST:
        vhost_id = int(escape(request.POST.get('vhost')))
        net_name = escape(request.POST.get('name'))
        VH = VHost.objects.get(id=vhost_id)

        if VH.VType.vendor == "VB":
            ntype = "intnet"
        elif VH.VType.vendor == "ZN":
            ntype = "portgroup"
        else:
            ntype = escape(request.POST.get('ntype'))

        if not VSwitch.objects.filter(VHost_id=vhost_id, name=net_name, type=ntype).exists():

            if VH.VType.vendor == "VB":
                new_net = VSwitch(
                    name=net_name,
                    VHost=VH,
                    type="intnet",
                )

console/templates/console/Old./form_create_vm_disk.html
{% extends 'console/base.html' %}


{% block content%}

<div class="content-wrapper">
    <section class="content-header"></section>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">New Virtual Machine (2/4)</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-md-12"> In order to create the Virtual Disk please fullfill the following data:</label>
                        </div>
                    </div>
                    <div class="row"></div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for"vm_datastore">Select a Datastore:</label>
                            </div>
                            <div class="col-md-4">
                                <select id="vm_datastore" aria-hidden="true" tabindex="-1" class="form-control select select2-hidden-accessible">
                                    {% for item in DSTORE %}
                                    <option value="{{ item.id }}" >{{item.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-2">
                                 <label for"vm_dsk_sz">Disk Size (in MB):</label>
                            </div>
                            <div class="col-md-4">
                                <input type="number" min="0" id="vm_dsk_sz" class="form-control" value="" style="width: 30%;">
                            </div>
                        </div><!-- ./form group -->
                    </div>
                    <div class="row">
                        <div class="form-group">
                            {% csrf_token %}
                            <input type="hidden" id="form_step" value="{{ STEP }}" readonly>
                            <input type="hidden"  id="vm_vhost_id" value="{{ VH.id }}" readonly>
                        </div><!-- ./form group -->
                    </div>
                </div><!-- .box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-8">
                        </div>
                        <div class="col-md-4">
                            <span class="btn-group pull-right">
                                <input type="button" id="reset_form" class="btn btn-danger" value="Reset">
                                <input type="button" id="back_form" class="btn btn-warning" value="Back">
                                <input type="button" id="cont_form" class="btn btn-primary" value="Continue">
                            </span>
                        </div>
                    </div>
                </div><!-- /.box-footer -->
            </div><!-- .box -->

        </div><!-- .col -->
    </div><!-- .row -->
</div><!-- .wrapper-->

{% endblock content %}

console/templates/console/Old./form_create_vm_net.html
{% extends 'console/base.html' %}

{% block content%}

<div class="content-wrapper">
    <section class="content-header"></section>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">New Virtual Machine (STEP 3/4)</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="iface_num">Select the number of Interfaces:</label>
                            </div>
                            <div class="col-md-6">
                                <select id="iface_num" aria-hidden="true" tabindex="-1" class="form-control select select2-hidden-accessible">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                            </div>
                        </div><!-- ./form group -->
                    </div>

                    <div class="row">
                        <div class="form-group">
                            {% csrf_token %}
                            <input class="form-control" type="hidden" id="form_step" value="{{ STEP }}" readonly>
                            <input class="form-control" type="hidden"  id="vm_vhost_id" value="{{ VH.id }}" readonly>
                         </div><!-- ./form group -->
                    </div>
                </div><!-- .box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-8">
                        </div>
                        <div class="col-md-4">
                            <span class="btn-group pull-right">
                                <input type="button" id="reset_form" class="btn btn-danger" value="Reset">
                                <input type="button" id="back_form" class="btn btn-warning" value="Back">
                                <input type="button" id="cont_form" class="btn btn-primary" value="Continue">
                            </span>
                        </div>
                    </div>
                </div><!-- /.box-footer -->
            </div><!-- .box -->

        </div>
        </div><!-- .col -->
    </div><!-- .row -->
</div><!-- .wrapper>

{% endblock content %}

console/templates/console/Old./form_create_vm_net_2.html
{% extends 'console/base.html' %}

{% block content%}

<div class="content-wrapper">
    <section class="content-header"></section>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">New Virtual Machine (STEP 3/4)</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="iface_num">Select the number of Interfaces:</label>
                            </div>
                            <div class="col-md-6">
                                <select id="iface_num" aria-hidden="true" tabindex="-1" class="form-control select select2-hidden-accessible">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                            </div>
                        </div><!-- ./form group -->
                    </div>

                    <div class="row">
                        <div class="form-group">
                            {% csrf_token %}
                            <input class="form-control" type="hidden" id="form_step" value="{{ STEP }}" readonly>
                            <input class="form-control" type="hidden"  id="vm_vhost_id" value="{{ VH.id }}" readonly>
                        </div><!-- ./form group -->
                    </div>
                </div><!-- .box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-8">
                        </div>
                        <div class="col-md-4">
                            <span class="btn-group pull-right">
                                <input type="button" id="reset_form" class="btn btn-danger" value="Reset">
                                <input type="button" id="back_form" class="btn btn-warning" value="Back">
                                <input type="button" id="cont_form" class="btn btn-primary" value="Continue">
                            </span>
                        </div>
                    </div>
                </div><!-- /.box-footer -->
            </div><!-- .box -->


        </div><!-- .col -->
    </div><!-- .row -->
</div><!-- .wrapper>

{% endblock content %}

console/templates/console/Old./form_network.html
{% extends 'console/base.html' %}


{% block content%}
  <script src="/static/js/net.js"></script>


  <div class="content-wrapper">
    <section class="content-header"></section>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">New Virtual Network</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="box-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Please confirm the following data:</h4>
                                </div>
                            </div><!-- .row -->
                            <div class="panel box box-primary">
                                <div class="box-header with-border">
                                    <h4 class="box-title">General Data</h4>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <label for="id_name">Name </label>
                                            </div>
                                            <div class="col-md-4">
                                                <input class="form-control" id="id_name" maxlength="30" name="name" type="text">
                                            </div>
                                            <div class="col-md-2">
                                                <label for="id_VHost">Virtual Host</label>
                                            </div>
                                            <div class="col-md-4">
                                                <select class="form-control" id="id_VHost">
                                                    <option value="0">-----------------</option>
                                                    {% for host in VH %}
                                                        <option value="{{ host.id }}">{{ host.name }}</option>
                                                    {%  endfor %}
                                                </select>
                                            </div>
                                        </div><!-- .form-group -->
                                    </div><!-- .row -->
                                </div><!-- .box body -->
                            </div><!-- .panel General Data -->
                            <div id="Net_Panel" style="display: none;">
                            <div class="panel box box-primary">
                                <div class="box-header with-border">
                                    <h2 id="np_title" class="box-title"></h2>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="form-group">
                                             <div class="col-md-2">
                                                <label for="id_Ntype">Net Type</label>
                                            </div>
                                            <div class="col-md-4">
                                                <select class="form-control" id="id_NType">
                                                </select>
                                            </div>
                                        </div><!-- .form-group -->
                                        <div id="new_vswitch" class="form-group">
                                        </div>

                                    </div><!-- .row -->
                                 </div><!-- .box body -->
                            </div><!-- .panel General Data -->
                            </div><!-- .Net-Panel -->

                        </div><!-- .box-group-->
                    </div><!-- .box-body-->
                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-8">
                            </div>
                            <div class="col-md-4">
                                <span class="btn-group pull-right">
                                    <input type="button" id="btn_create_net" class="btn btn-primary " value="Create">
                                </span>
                            </div>
                        </div>
                    </div><!-- /.box-footer -->
                </div><!-- /.box -->

            {% csrf_token %}

            </div><!-- .col -->
            <div class="col-md-2"></div>
        </div><!-- .row -->
  </div><!-- .wrapper-->





{% endblock content %}